name = "Iris (Hide Parens)"
grammar = "iris"
path_suffixes = []
line_comments = [";;"]
tab_size = 4
hard_tabs = false
word_characters = ["_", "-", ".", "!", "?", "<", ">", "=", "*", "+", "/"]
language_servers = ["iris-lsp"]
