id = "iris"
name = "Iris Language Support"
version = "0.1.5"
schema_version = 1
description = "Syntax highlighting and editor support for IRIS (.iris) files."
repository = "https://github.com/ljack/iris-zed"
authors = ["Iris Contributors <dev@iris-lang.org>"]
themes = []
icon_themes = []
languages = ["languages/iris", "languages/iris-dim", "languages/iris-hide"]
capabilities = []

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.iris]
repository = "file:///Users/jarkko/_dev/iris-zed/.git"
rev = "21fb30113d3f2a86c04c1dba287da1daf825e054"
path = "tree-sitter-iris"

[language_servers.iris-lsp]
name = "IRIS Language Server"
language = "Iris"

[context_servers]

[agent_servers]

[slash_commands.iris-parens]
name = "iris-parens"
description = "Show how to switch Iris paren visibility modes."
tooltip_text = "Switch paren mode (normal|dim|hide)"
requires_argument = false
